# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j75jVSjVy8uMrDvj63Q6-WQfFDwSWz06
"""

# Escreva um programa que inverta os caracteres de um string.

# a) Essa string pode ser informada através de qualquer entrada de sua preferência ou pode ser previamente definida no código;

# b) Evite usar funções prontas, como, por exemplo, reverse;


palavra = input("Oi! Vamos inverter sua palavra. \nDigite uma palavra: ")
palavra_invertida = palavra[::-1]
print("Palavra invertida:", palavra_invertida)