# -*- coding: utf-8 -*-
"""Questão 02 - Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e20XFSCbnnYf_uYwCrAbULxBrpb3Gf56
"""

# Dado a sequência de Fibonacci, onde se inicia por 0 e 1 e o próximo valor sempre será a soma dos 2 valores anteriores
# (exemplo: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34...), escreva um programa na linguagem que desejar onde, informado um número, ele calcule a sequência de Fibonacci e
# retorne uma mensagem avisando se o número informado pertence ou não a sequência.
# IMPORTANTE:
# Esse número pode ser informado através de qualquer entrada de sua preferência ou pode ser previamente definido no código;

def fibonacci(n):
    fibonacci = [0, 1]
    while fibonacci[-1] < n:
        fibonacci.append(fibonacci[-1] + fibonacci[-2])
    return fibonacci

def pertence_sequencia(numero, sequencia):
    if numero in sequencia:
        return True
    else:
        return False

numero = int(input("Oi!!! Você conhece a sequência de Fibonacci? \nDigite um número e vou verificar se ele pertence à sequência: "))
sequencia_fibonacci = fibonacci(numero)
pertence = pertence_sequencia(numero, sequencia_fibonacci)

if pertence:
    print(sequencia_fibonacci)
    print(f"{numero} pertence à sequência de Fibonacci.")
else:
    print(f"{numero} não pertence à sequência de Fibonacci.")